__tests__/rudderstack.spec.ts
package-lock.json
package.json
src/rudderstack.ts

This reverts commit bade568496a5dd45523941ab73316f656ee68fbe.

Revert "Use beta rudder sdk (#6)"

---

README.md
package.json
src/analytics.ts
src/growthbook.ts
src/types.ts

in deriv-app we have to setAttributes several times, in this case we have to handle all undefined's properties
here is example with quick tests how it works

refactor: handle undefined on setAttributes params

---

package.json
src/analytics.ts
src/types.ts

[-] Make growthbook optional while initializing the analytics instance

feat: make growthbook optional

---

package.json
src/types.ts

* Change types for traders hub tracking flow ( we recently check the requirements of the tracking and after going through each step, found out that there's one parameter which is wrong, so we need to add the proper type accordingly to correct the flow )

feat: adjust types for tradershub tracking

---

package.json
src/types.ts

add types for dbot quick strategy

[CRO] Types:

---

package.json
src/types.ts

add types for that pr https://github.com/binary-com/deriv-app/pull/12339

[CRO] NikitK/CRO-357/Questionary types

---

package.json
src/growthbook.ts

title is actually a description. quick fix

[CRO] tracking callback should always call with rudderstack

---

src/types.ts

updated types for quick strategy and dashboard of bot-web-ui package.

[BOT] Shafin/Farabi/BOT1253/BOT1252/Update--types-for-DBOT

---

src/types.ts

- To add types for ContractsSetupForm analytics to `TEvents`.

[DTRA] Maryia/DTRA-904/feat: add types for ContractsSetupForm analytics

---

package-lock.json
package.json

- To update package version to 1.4.12.

Maryia/build: update package version to 1.4.12

---

package.json
src/analytics.ts
src/growthbook.ts
src/rudderstack.ts
src/types.ts

To update types for partners, types for cache and config id, work with undefined fields

[CRO] Nikitk/partners signup providing new param and some cleanup

---

package-lock.json
package.json
src/analytics.ts
src/growthbook.ts
src/types.ts

- Add URL redirect support by upgrading the growthbook package
- Add types for the new experiment tracking

[CRO] Amir/add url redirect support and type changes

---

README.md
package.json
src/analytics.ts
src/growthbook.ts
src/types.ts

- Add `growthbookOptions` parameter in the readme doc
- Change version to `1.5.0`
- Add `url` attribute to target the audience

[CRO] Amir/add doc and version update to 1.5.0

---

package.json
src/types.ts

Tracking specs for Traders hub

Aswathy/CRO-470/Tracking specs for Traders hub

---

package.json
src/types.ts

Tracking specs types for `ce_passkey_account_settings_form` and `ce_passkey_effortless_form`

Aswathy/UPM-931/fix: passkey types added

---

src/types.ts

updated types for dbot package

[BOT]/Farabi/BOT-1444/Updated rudder-stack types

---

src/types.ts

- Fixed type issues in Analytical package for these CE:
```
ce_tradershub_dashboard_form 
ce_tradershub_banner
ce_passkey_account_settings_form 
ce_passkey_effortless_form
ce_tradershub_popup
```

Aswathy/CRO-593/fix: analytical type fpr some schemas

---

.github/workflows/publish_to_npm.yml
package-lock.json
package.json

* This is to update growthbook sdk to version 1
* I also updated the workflow to get triggered on merge to beta branch

Ako/ update growthbook to v1

---

src/types.ts

**Add `ce_cashier_deposit_onboarding_form` event:**
```
type TCashierDepositOnboardingFormAction = {
action?: 'open' | 'open_deposit_subpage' | 'click_deposit_card' | 'click_copy_crypto_address'
form_name?: 'ce_cashier_deposit_onboarding_form'
currency?: string
deposit_category?: string
login_id?: string
}
```

feat: :sparkles: add TCashierDepositOnboardingFormAction event type

---

package-lock.json
package.json

Upgrade growthbook version from 1.0.1 to 1.1.0

feat: update growthbook version

---

src/analytics.ts

There was a typeError `js_cookie_1.default.getJSON is not a function`
So Instead of relying on getJSON,we can use Cookies.get() and parse the result as JSON if needed

fix: CRO-720/fix: country getJson issue

---

src/analytics.ts
src/rudderstack.ts
src/types.ts

- Added `disableRudderstacAMD` to Analytics.initialise() which is exposed to the consumer app and is the entry point

feat: FEWP-249/fix clevertap load issue in outsystem

---

src/analytics.ts

Failed to fetch: GET https://www.cloudflare.com/cdn-cgi/trace

fix: cloudfare fetching issue

---

src/analytics.ts

Resolving the console error encountered in the Deriv Analytics application related to fetching the country information from Cloudflare.

Hirad/FEWP-299/ Adding condition to cover cases which we receive null

---

src/types.ts

Modify types for rudderstack events for dtrader

feat: add types for dtrader tracking

---

package-lock.json
package.json

- Updated `@deriv-com/utils` to version `0.0.42`

Shayan/updated @deriv-com/utils to the latest version

---

src/growthbook.ts

Changes:
- added `url` as an optional input to `reapplyExperiment()`

feat: updated reapplyExperiment

---

src/rudderstack.ts

- added expiry date for rudderstack anonymous_id and set it to 2 years

chore: added expiry date to rudderstack anonymous_id

---

src/analytics.ts
src/growthbook.ts
src/types.ts

#changes
- Introduced a new property, `account_mode`, which can be set to either **demo** or **real**.

Shayan/ CRO-938/ introduced new tracking attribution - account_mode

---

__tests__/rudderstack.spec.ts
src/analytics.ts
src/rudderstack.ts

using Rudderstack [onLoaded callback function](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#onloaded)

fix: fixed identify call issue
